Start sketching webassembly bindings.
Requires migrating to `thiserror` as `anyhow::Error` does not implement
`std::error::Error` which means it cannot be transparently converted to
`JsError`.